nama = input("Nama\t\t: ")
nim = input("Nim\t\t: ")
kelas = input("Kelas Pararel\t: ")
ttl = input("ttl\t\t: ")
alamat = input("Alamat\t\t: ")
hobby = input("Hobby\t\t: ")
nohp = input("No. HP\t\t: ")
print("\nNama\t\t\t: ", nama)
print("NIM\t\t\t: ", nim)
print("Kelas Pararel\t\t: ", kelas)
print("Tempat/Tanggal Lahir\t: ", ttl)
print("Alamat\t\t\t: ", alamat)
print("Hobby\t\t\t: ", hobby)
print("No. HP\t\t\t: ", nohp)
